### ISSUE TITLE
nd4s slicing is broken

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#52]
The slicing operation in nd4s is broken. Consider the following example :

    val nd = Nd4j.create((0d to 8d by 1d).toArray, Array(4, 2))
    println(nd)
    println(nd(0 -> 2, 2 -> 4))

OUTPUT : 
[[0.00,1.00]
 [2.00,3.00]
 [4.00,5.00]
 [6.00,7.00]]

[[0.00,2.00]
 [4.00,6.00]]

Note that what should be printed out from the slicing operation is 
[[0.00,1.00]
 [2.00,3.00]

The error seems to be coming from TupleRange in Implicits.
Atleast that's the api call I used to trace through the error before I got lost in the implicits conversions.

**Comment by taisukeoe** [comment]
Let me confirm why it should return:
[[0.00,1.00]
[2.00,3.00]]

Since `nd(0 -> 2, 2 -> 4)`  operations is not relevant for INDArray with shape (4,2), since index `2 -> 4` is out of index in its column. 
So its operation in nd4s / nd4j return wrong NDArray and would be a bug. It should return a empty NDArray or throw a Exception.

In case you mean `nd(2 -> 4, 0 -> 2)`, it returns correct NDArray as follows.

```scala
scala> val nd = Nd4j.create((0d to 8d by 1d).toArray, Array(4, 2))
nd: org.nd4j.linalg.api.ndarray.INDArray =
[[0.00,1.00]
 [2.00,3.00]
 [4.00,5.00]
 [6.00,7.00]]

scala> nd(2->4,0->2)
res1: org.nd4j.linalg.api.ndarray.INDArray =
[[4.00,5.00]
 [6.00,7.00]]
```

Ref: Equivalent NumPy slicing operation.

```python
>>> import numpy as nm

>>> arr = nm.array([[0,1],[2,3],[4,5],[6,7]])
>>> arr
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

#Returns empty NDArray
>>> arr[0:2,2:4]
array([], shape=(2, 0), dtype=int64)

>>> nd = arr[2:4,0:2]
>>> nd
array([[4, 5],
       [6, 7]])
```

**Comment by taisukeoe** [comment]
Hi @rahulpalamuttam , What do you think about it?

**Comment by rahulpalamuttam** [comment]
Hi @taisukeoe I agree, this makes sense.
I guess the only other thing to check then is that it follows numpy slicing convention for multiple slicing as well. 
I'll close the issue.
